services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cemos2028_backend
    command: >
      sh -c "
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn django_cemos2028.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:18
    container_name: postgres_cemos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ðŸ”¹ Novo container apenas para build do Angular
  frontend-build:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cemos2028_frontend_build
    volumes:
      - ./frontend/dist:/app/dist
    command: ["/bin/true"]
    networks:
      - app_network

  # ðŸ”¹ Nginx reverso principal com HTTPS e proxy para Django
  nginx:
    image: nginx:latest
    container_name: cemos2028_nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend-build
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - static_volume:/static
    networks:
      - app_network

volumes:
  static_volume:
  postgres_data:

networks:
  app_network:
    driver: bridge
