services:
  # ==========================================
  # ðŸ”¹ BACKEND DJANGO
  # ==========================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cemos2028_backend
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn django_cemos2028.wsgi:application --bind 0.0.0.0:8000
      "
    ports:
      - "8000:8000"          # âœ… Permite testes diretos do backend no host
    volumes:
      - ./backend:/app:rw
      - static_volume:/app/static
    environment:
      # ðŸ”¹ Banco de dados
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      # ðŸ”¹ SuperusuÃ¡rio Django
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin123
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      # ðŸ”¹ ConfiguraÃ§Ãµes opcionais
      PYTHONUNBUFFERED: 1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network


  db:
    image: postgres:18
    container_name: postgres_cemos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    # âœ… caminho atualizado para o Postgres 18+
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ðŸ”¹ Nginx reverso principal com proxy para Django e servindo Angular
  nginx:
    image: nginx:latest
    container_name: cemos2028_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - static_volume:/app/static:ro      
    networks:
      - app_network

volumes:
  static_volume:
  postgres_data:

networks:
  app_network:
    driver: bridge
