services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cemos2028_backend
    command: >
      sh -c "
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn django_cemos2028.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:18
    container_name: postgres_cemos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    # âœ… caminho atualizado para o Postgres 18+
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ðŸ”¹ Nginx reverso principal com proxy para Django e servindo Angular
  nginx:
    image: nginx:latest
    container_name: cemos2028_nginx
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - static_volume:/static
    networks:
      - app_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cemos2028.rule=Host(`cemos2028.site`,`www.cemos2028.site`)"
      - "traefik.http.routers.cemos2028.entrypoints=websecure"
      - "traefik.http.routers.cemos2028.tls=true"
      - "traefik.http.services.cemos2028.loadbalancer.server.port=80"

volumes:
  static_volume:
  postgres_data:

networks:
  app_network:
    driver: bridge
