services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cemos2028_backend
    command: >
      sh -c "
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn django_cemos2028.wsgi:application --bind 0.0.0.0:8000 --reload
      "
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=@cemos2028
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:18
    container_name: postgres_cemos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - ./postgres_data:/var/lib/postgresql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  dash:
    build:
      context: ./dash
      dockerfile: Dockerfile
    container_name: cemos2028_dash
    restart: unless-stopped
    ports:
      - "8050:8050"
    environment:
      - DASH_API_URL=http://backend:8000/api/metrics/
      - DASH_REFRESH_SECONDS=60
    depends_on:
      - backend
    networks:
      - app_network

  # ðŸ”¹ Nginx para desenvolvimento (HTTP simples, sem SSL)
  nginx:
    image: nginx:latest
    container_name: cemos2028_nginx
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
      - "8088:8088"
      - "8089:8089"
    volumes:
      # FRONTEND 1 â€“ CEMOS2028    
      - ./frontend-cemos/dist/frontend/browser:/usr/share/nginx/cemos2028
      # FRONTEND 2 â€“ AUDITAPRO
      - ./frontend-audita/dist/frontend/browser:/usr/share/nginx/audita
      # NGINX CONFIG - DESENVOLVIMENTO
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      # DJANGO STATIC
      - static_volume:/static
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: cemos2028_prometheus_dev
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./observability/prometheus/prometheus.dev.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - app_network

  grafana:
    image: grafana/grafana:11.1.0
    container_name: cemos2028_grafana_dev
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=@cemos2028
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app_network


volumes:
  static_volume:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  app_network:
    driver: bridge
